name: Create EC2 instance for Java API

on:
  pull_request:
    types: opened
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS Cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create private key file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa_ec2
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa_ec2
          chmod 600 ~/.ssh/id_rsa_ec2
          cat ~/.ssh/id_rsa_ec2

      - name: Get Description from pull request
        run: |
          export DESCRIPTION=$(echo "${{ github.event.pull_request.body }}")
          echo "Description: $DESCRIPTION"
          echo "DESCRIPTION=$DESCRIPTION" >> $GITHUB_ENV

      - name: Get Destroy infra from tfvars
        run: |
          export DESTROY_INFRA=$(cat infra/terraform.tfvars | grep destroy_infra | cut -d'=' -f2 | tr -d '[:space:]')
          echo "Destroy Infra: DESTROY_INFRA"
          echo "DESTROY_INFRA=DESTROY_INFRA" >> $GITHUB_ENV

      - name: Destroy infra if variable is set
        if: ${{ env.DESTROY_INFRA == 'true' }}
        run: |
          cd infra
          terraform init
          terraform destroy -auto-approve
          
      - name: Create EC2 instance if destroy variable is not set
        if: ${{ env.DESTROY_INFRA != 'true' }}
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve

      - name: Set PR msg
        run: |
          echo "MSG=A infra foi ${{ env.DESTROY_INFRA == 'true' && 'destruída' || 'criada' }} com sucesso!" >> $GITHUB_ENV

      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              issue_number: ${{ github.event.pull_request.number }},
              repo: context.repo.repo,
              body: `${{ env.MSG }}`
            })
          
